### ISSUE TITLE
Usage with CustomBusinessDay

### ISSUE THREAD

**Issue by bacharsam** [rsheftel/pandas_market_calendars#179] opened 2022-02-15 12:31 UTC
Hi - I am using  the NYSE calendar in my model
I am using CustomBusinessDay to create the offsets 
Recently , my functionality stopped working  properly in COLAB. After I set the the frequency of my timeseries dataset I am getting dataset (df) with null values
Has something changed in the way the calendar & offsets should be defined ?
Below is my code :

def set_calendar():
   nyse = mcal.get_calendar('NYSE')
   holidays = nyse.holidays()
   nyse_holidays=holidays.holidays[:]  
  nyse_us = pd.offsets.CustomBusinessDay(calendar=nyse, holidays=nyse_holidays)
  return nyse_us 

nyse_us = set_calendar()
df = load_csv_file(dataset_dir,dataset_file)
df .sort_values('Date', inplace=True)
df .set_index('Date' , inplace=True)
df =df .asfreq(nyse_us)

**Comment by Stryder-Git** [comment] 2022-02-15 16:22
Hi @bacharsam, I don't have the impression that the problem has to do with this package. You are creating a new `CustomBusinessDay` object, which is a pandas object, and then you are using it to change the frequency on what I assume to be a regular pandas `DataFrame`.

The only way that I can get a dataframe of NaNs after a call to .asfreq, is if the index of the DataFrame is not actually a DatetimeIndex but in string type for example.
Please make sure that the "Date" column that you are setting as index is actually a datetime type (you can convert it with pd.to_datetime). 

I am going to close this issue, because I don't think this package is the cause of the problem, but feel free to reopen it if I am wrong.

**Closed by Stryder-Git** 2022-02-15 16:22 UTC
