### ISSUE TITLE
Please update the pandas version dependency 

### ISSUE THREAD

**Issue by badal8381** [rsheftel/pandas_market_calendars#325] opened 2024-02-02 15:04 UTC
I'm using few packages which use latest version of pandas but the pandas_market_calender explicitly uninstall the latest version of pandas and install the version >=1 and <= 2. Please take action into this.

**Comment by kentonself** [comment] 2024-02-08 04:13
Is this a duplicate of [315](https://github.com/rsheftel/pandas_market_calendars/issues/315)?

If so, there is a workaround in the comments if you can't wait for it to be uploaded to pypi.

**Comment by badal8381** [comment] 2024-02-09 14:08
Yeah looks similar issue. Thanks for the response

**Comment by rsheftel** [comment] 2024-02-10 22:19
v.4.4.0 is published to PyPi and works with Python 3.12 and Pandas 2.2.0

**Closed by rsheftel** 2024-02-10 22:19 UTC

**Comment by badal8381** [comment] 2024-02-11 02:39
That's great thank you so much
