### ISSUE TITLE
days_at_time throws exception if there are no open days, proposed change included

### ISSUE THREAD

**Issue by dfhtqepd** [rsheftel/pandas_market_calendars#39] opened 2018-06-30 19:54 UTC
Hi,

Calling the .schedule() method will throw an exception if there are no business days between start_date and end_date. For example

`nyse_cal = mcal.get_calendar('NYSE')`
`nyse_schedule = nyse_cal.schedule(start_date = '2018-06-30',end_date = '2018-06-30')`

The specific error message is
`  File "/home/username/.local/lib/python3.5/site-packages/pandas_market_calendars/market_calendar.py", line 312, in days_at_time`
`    return pd.DatetimeIndex(days).tz_localize(tz).tz_convert('UTC')`
`  File "/home/username/.local/lib/python3.5/site-packages/pandas/core/indexes/datetimes.py", line 2379, in tz_localize`
`    raise TypeError("Already tz-aware, use tz_convert to convert.")`
`TypeError: Already tz-aware, use tz_convert to convert.`

Would it be appropriate to change the relevant code section as follows?
`        if pd.DatetimeIndex(days).tzinfo is not None:`
`            return pd.DatetimeIndex(days).tz_convert('UTC')`
`        else:`
`            return pd.DatetimeIndex(days).tz_localize(tz).tz_convert('UTC')`

Apologies in advance if this isn't the right format in which to bring this up. I'm not confident enough in my proposed change to submit a pull request (if that's even the correct term) ...

**Comment by rsheftel** [comment] 2018-07-01 16:40
Right now that is the intended behavior, to throw an exception if there are no valid dates in the requested range. But given that (1) the error is very difficult to understand and (2) several people have the same question I will probably update to just return a blank DataFrame.

**Comment by dfhtqepd** [comment] 2018-07-01 18:17
Thanks very much! And most of all, thank you very much for creating and maintaining this excellent package! It is really great ... super useful and fills an important unmet need.

**Comment by rsheftel** [comment] 2018-07-02 11:53
This is now fixed in v0.19 commit - 8a95494a0d3d7f7acc10ea2903eeeb5a80702a72

**Closed by rsheftel** 2018-07-02 11:53 UTC
Labels: enhancement, question
